steps:
  # Backend Build and Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Frontend Build and Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', 'frontend']
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/frontend:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Backend Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'memoria-os-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Frontend Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'memoria-os-frontend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/memoria-os/frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

substitutions:
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
