line-length = 100
target-version = "py311"

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "S",   # flake8-bandit
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "D",   # pydocstyle (Google Style)
]
ignore = [
    "ANN101", # Missing type annotation for 'self' in method
    "ANN102", # Missing type annotation for 'cls' in classmethod
    "ANN401", # Dynamically typed expressions (Any) are disallowed
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
]

[lint.pydocstyle]
convention = "google"
